app:
  name: Shared base config for all microservices in Dev enviornment
  environment: Dev
shared:
  config:
    rebate-rate: 12
spring:
  datasource:
    url: jdbc:postgresql://${pg-host}:${pg-port}/${pg-database}
    username: ${pg-username}
    password: ${pg-password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
